### PR TITLE
Added a telegram echo bot

### PR DESCRIPTION
**Pull request by jerojero**
I added a python script that lets you do a simple echo bot on telegram. Uses /start and /stop to start and stop sending echoing messages.

### CODE REVIEW

**Comment by mbartlet** [comment]
Looks good! I think the reason `.gitignore` wasn't working as intended was because it's in the .idea/ folder from looks of it. Would you mind adding ".idea" to the `.gitignore` in the root of the repo and then `git rm .idea`, and push those changes?

**Review by mbartlet — CHANGES_REQUESTED** [review]
`git rm` .idea files :^)

**Comment by jerojero** [comment]
I think I did it. I pushed the changes into my forked repository, will this pull request take that into account or do I have to pull again?

**Review by mbartlet — APPROVED** [review]

**Comment by mbartlet** [comment]
Looks good, I've merged

**Pull request merged**
